[api]
schemas = ["public", "student", "staff", "grading", "reporting", "file_manager", "chat"]

[auth]
enabled = true

[auth.email]
otp_length = 8

[auth.email.template.magic_link]
subject = "Your GradeBook Login Code"
content_path = "./supabase/templates/magic-link.html"

[auth.email.template.confirmation]
subject = "Your GradeBook Login Code"
content_path = "./supabase/templates/otp-code.html"

[storage.buckets.images]
public = true
file_size_limit = "5MiB"
allowed_mime_types = ['image/jpeg', 'image/png', 'image/webp']

[storage.buckets.report-books]
public = false

[storage.buckets.file-manager]
public = false
file_size_limit = "50MiB"