import { Pressable, StyleSheet, View } from "react-native";
import { useRouter, type Href } from "expo-router";
import {
  Megaphone,
  MessageSquare,
  FolderClosed,
  UsersRound,
  BookText,
  CalendarDays,
  GraduationCap,
  ShieldCheck,
  ChevronRight,
  type LucideProps,
} from "lucide-react-native";
import type { ComponentType } from "react";
import { useTheme } from "@/theme/ThemeProvider";
import { usePermissions } from "@/providers/PermissionsProvider";
import { Screen } from "@/components/layout/Screen";
import { Card } from "@/components/ui/Card";
import { Text } from "@/components/ui/Text";

interface MenuItem {
  // String path; cast to Href at navigation time. The typed-route union is
  // regenerated by the Expo dev server, so these are cast rather than literal.
  href: string;
  label: string;
  description: string;
  icon: ComponentType<LucideProps>;
  adminOnly?: boolean;
}

const ITEMS: MenuItem[] = [
  {
    href: "/announcements",
    label: "Announcements",
    description: "School-wide notices",
    icon: Megaphone,
  },
  {
    href: "/chat",
    label: "Messages",
    description: "Conversations with staff",
    icon: MessageSquare,
  },
  {
    href: "/files",
    label: "Files",
    description: "Documents and shares",
    icon: FolderClosed,
  },
  {
    href: "/staff",
    label: "Staff",
    description: "Members and join requests",
    icon: UsersRound,
  },
  {
    href: "/subjects",
    label: "Subjects",
    description: "Manage subjects",
    icon: BookText,
  },
  {
    href: "/academic-calendar",
    label: "Academic Calendar",
    description: "Years and terms",
    icon: CalendarDays,
  },
  {
    href: "/grade-scales",
    label: "Grade Scales",
    description: "Grading bands",
    icon: GraduationCap,
    adminOnly: true,
  },
  {
    href: "/roles",
    label: "Roles",
    description: "Permissions and custom roles",
    icon: ShieldCheck,
    adminOnly: true,
  },
];

export default function MoreScreen() {
  const router = useRouter();
  const { colors } = useTheme();
  const { isAdmin } = usePermissions();

  const items = ITEMS.filter((i) => !i.adminOnly || isAdmin);

  return (
    <Screen title="More" description="Everything else in your school">
      <View style={{ gap: 8 }}>
        {items.map((item) => {
          const Icon = item.icon;
          return (
            <Pressable
              key={item.label}
              onPress={() => router.push(item.href as Href)}
              style={({ pressed }) => ({ opacity: pressed ? 0.7 : 1 })}
            >
              <Card>
                <View style={styles.row}>
                  <View style={[styles.iconWrap, { backgroundColor: colors.muted }]}>
                    <Icon size={20} color={colors.foreground} />
                  </View>
                  <View style={{ flex: 1 }}>
                    <Text weight="600">{item.label}</Text>
                    <Text variant="muted" style={{ marginTop: 1, fontSize: 13 }}>
                      {item.description}
                    </Text>
                  </View>
                  <ChevronRight size={20} color={colors.mutedForeground} />
                </View>
              </Card>
            </Pressable>
          );
        })}
      </View>
    </Screen>
  );
}

const styles = StyleSheet.create({
  row: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    padding: 14,
  },
  iconWrap: {
    width: 40,
    height: 40,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
  },
});
