upstream backend_load_balancer {
    server 127.0.0.1:3004;
    server 127.0.0.1:3005;
    server 127.0.0.1:3006;
}


server {
    listen 80;

    location / {
        proxy_pass http://backend_load_balancer;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

}